#!/bin/bash

# 🚀 GUIDE DE DÉMARRAGE - Tests Manuels

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🚀 GUIDE POUR TESTER L'IMPLÉMENTATION BREAKDOWN"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ PRÉ-REQUIS:"
echo "   • PHP 8.4+"
echo "   • MySQL/MariaDB"
echo "   • Laravel 12"
echo ""

echo "ÉTAPE 1: Démarrer le serveur Laravel"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "$ cd /home/nicodeme/Bureau/D-Clic-2025/garage-laravel/GESTION_CLIENTS_APP"
echo "$ php artisan serve"
echo ""
echo "📌 Serveur accessible à: http://localhost:8000"
echo ""

echo "ÉTAPE 2: Accéder à l'application"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "URL: http://localhost:8000"
echo ""

echo "ÉTAPE 3: Se connecter EN TANT QUE CLIENT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📧 Email: [voir seeders pour données test]"
echo "🔐 Mot de passe: [voir seeders pour données test]"
echo ""
echo "💡 Ou créer un compte client via:"
echo "   $ php artisan tinker"
echo "   > User::create(['name' => 'Test', 'email' => 'test@test.com', 'role' => 'client', ...])"
echo ""

echo "ÉTAPE 4: Naviguer vers le formulaire de panne"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "URL: http://localhost:8000/breakdowns/create"
echo ""

echo "ÉTAPE 5: TESTER LES CHAMPS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "A) VÉHICULE"
echo "   ├─ Cliquez sur le dropdown"
echo "   ├─ Sélectionnez un véhicule"
echo "   └─ ✅ Le véhicule reste sélectionné"
echo ""

echo "B) DESCRIPTION"
echo "   ├─ Entrez 'Le moteur fait un bruit bizarre'"
echo "   ├─ Max 1000 caractères"
echo "   └─ ✅ La description s'affiche"
echo ""

echo "C) TÉLÉPHONE"
echo "   ├─ Essayez: '+33 6 12 34 56 78'"
echo "   ├─ Ou: '06 12 34 56 78'"
echo "   ├─ Ou: '(06) 12-34-56-78'"
echo "   └─ ✅ Le numéro est accepté"
echo ""

echo "D) LOCALISATION"
echo "   ├─ Entrez: 'Avenue de la République, 75000 Paris'"
echo "   ├─ Max 255 caractères"
echo "   └─ ✅ La localisation s'affiche"
echo ""

echo "E) DÉPANNAGE OUI/NON"
echo "   ├─ Cliquez sur 'NON'"
echo "   │  └─ Le sélecteur technicien est MASQUÉ"
echo "   │"
echo "   ├─ Cliquez sur 'OUI'"
echo "   │  └─ Le sélecteur technicien APPARAÎT"
echo "   │     ├─ Barre de recherche visible"
echo "   │     ├─ Grille de cartes visible"
echo "   │     └─ Photos des techniciens affichées"
echo "   │"
echo "   └─ ✅ L'affichage bascule correctement"
echo ""

echo "F) RECHERCHE TECHNICIEN"
echo "   ├─ Taper dans la barre: 'dupont'"
echo "   ├─ Les résultats se filtrent EN TEMPS RÉEL"
echo "   ├─ Affiche: 'Jean Dupont - Moteur' (ou autre)"
echo "   ├─ Cliquer sur la carte"
echo "   ├─ Le radio button se coche automatiquement"
echo "   └─ ✅ La recherche fonctionne + sélection OK"
echo ""

echo "ÉTAPE 6: SOUMETTRE LE FORMULAIRE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Remplissez tous les champs"
echo "✅ Cliquez sur 'Signaler la panne'"
echo ""

echo "ÉTAPE 7: VÉRIFIER LA CRÉATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Redirection vers /breakdowns/{id}"
echo "✅ Message de succès: 'Votre panne enregistrée...'"
echo "✅ Numéro de téléphone affiché dans le message"
echo ""

echo "ÉTAPE 8: VÉRIFIER LA BD"
echo "━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Entrez dans Tinker:"
echo "$ php artisan tinker"
echo ""
echo "Vérifiez que la panne existe:"
echo "> Breakdown::latest()->first();"
echo ""
echo "Résultat attendu:"
echo "  {#1234"
echo "    'user_id' => <votre_id>,                    ✅"
echo "    'vehicule_id' => <vehicule_id>,             ✅"
echo "    'description' => 'Le moteur...',            ✅"
echo "    'phone' => '+33 6 12 34 56 78',             ✅ NOUVEAU"
echo "    'location' => 'Avenue République...',       ✅ NOUVEAU"
echo "    'needs_technician' => 1,                    ✅ NOUVEAU"
echo "    'technicien_id' => 5,                       ✅"
echo "    'status' => 'pending',                      ✅"
echo "    'is_approved' => false,                     ✅"
echo "  }"
echo ""

echo "ÉTAPE 9: TESTER LES RESTRICTIONS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Se connecter en tant que GESTIONNAIRE CLIENT:"
echo "📌 URL: http://localhost:8000/breakdowns/create"
echo "❌ Résultat attendu: 403 Forbidden"
echo ""
echo "Se connecter en tant que RESPONSABLE SERVICES:"
echo "📌 URL: http://localhost:8000/breakdowns/create"
echo "❌ Résultat attendu: 403 Forbidden"
echo ""
echo "Se connecter en tant que ADMIN:"
echo "📌 URL: http://localhost:8000/breakdowns/create"
echo "❌ Résultat attendu: 403 Forbidden"
echo ""

echo "ÉTAPE 10: TESTS AUTOMATISÉS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Exécuter les tests:"
echo "$ php artisan test"
echo ""
echo "Ou juste les tests de breakdown:"
echo "$ ./vendor/bin/phpunit tests/Feature/BreakdownCreationTest.php --no-coverage"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✅ IMPLÉMENTATION TESTÉE ET VALIDÉE!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 FICHIERS À VÉRIFIER:"
echo "  1. app/Http/Controllers/BreakdownController.php"
echo "  2. app/Models/Breakdown.php"
echo "  3. resources/views/breakdowns/create.blade.php"
echo "  4. database/migrations/2026_01_24_000001_add_fields_to_breakdowns_table.php"
echo ""
echo "📚 DOCUMENTATION:"
echo "  • IMPLEMENTATION_COMPLETE.md"
echo "  • IMPLEMENTATION_BREAKDOWN_COMPLETE.md"
echo "  • BREAKDOWN_FINAL_SUMMARY.txt"
echo ""
